#!/usr/bin/env bash
#
# dep-lens installer: builds the Rust core and the Node CLI from this
# repository, installs a launcher into ~/.local/bin, and wires up PATH for
# your shell (fish, zsh, or bash) so the `dep-lens` command just works.
#
# Usage:
#   ./install.sh              install or update
#   ./install.sh --uninstall  remove the launcher
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
LAUNCHER="${BIN_DIR}/dep-lens"

say()  { printf '%s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- uninstall
if [ "${1:-}" = "--uninstall" ]; then
    if [ -e "$LAUNCHER" ]; then
        rm -f "$LAUNCHER"
        say "removed $LAUNCHER"
    else
        say "nothing to remove: $LAUNCHER does not exist"
    fi
    say "note: the ~/.local/bin PATH entry in your shell config was left in"
    say "place; it is harmless and shared with other tools."
    exit 0
fi

# ------------------------------------------------------------------- OS
OS="$(uname -s)"
case "$OS" in
    Linux|Darwin) ;;
    MINGW*|MSYS*|CYGWIN*)
        fail "Windows detected. Run 'install.ps1' from PowerShell instead, or use 'npm install -g dep-lens' (once published), or run this script inside WSL."
        ;;
    *)
        fail "unsupported operating system: $OS"
        ;;
esac
say "[1/5] operating system: $OS"

# ---------------------------------------------------------- prerequisites
command -v node  >/dev/null 2>&1 || fail "node not found. Install Node.js >= 18.18 first."
command -v npm   >/dev/null 2>&1 || fail "npm not found. It normally ships with Node.js."
command -v cargo >/dev/null 2>&1 || fail "cargo not found. Install Rust from https://rustup.rs first."

node -e 'const [maj, min] = process.versions.node.split(".").map(Number);
process.exit(maj > 18 || (maj === 18 && min >= 18) ? 0 : 1);' \
    || fail "Node.js >= 18.18 required, found $(node --version)."
say "[2/5] prerequisites: node $(node --version), $(cargo --version | cut -d' ' -f1-2)"

# ------------------------------------------------------------------ build
say "[3/5] building Rust core (cargo build --release)..."
(cd "$REPO_ROOT" && cargo build --release --quiet)

say "[4/5] building Node CLI (npm install + tsc)..."
(cd "$REPO_ROOT" && npm install --silent && npm run build:cli --silent)

CORE_BINARY="${REPO_ROOT}/target/release/dep-lens-core"
CLI_ENTRY="${REPO_ROOT}/packages/dep-lens/dist/cli.js"
[ -x "$CORE_BINARY" ] || fail "build finished but $CORE_BINARY is missing"
[ -f "$CLI_ENTRY" ]   || fail "build finished but $CLI_ENTRY is missing"

# -------------------------------------------------------------- launcher
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/sh
# dep-lens launcher generated by install.sh; points at the working tree at
# ${REPO_ROOT}. Re-run install.sh after moving the repository.
export DEP_LENS_BINARY="${CORE_BINARY}"
exec node "${CLI_ENTRY}" "\$@"
LAUNCHER_EOF
chmod 755 "$LAUNCHER"
say "[5/5] launcher installed: $LAUNCHER"

# ------------------------------------------------------------------ PATH
add_line_once() {
    # add_line_once <file> <line>
    if [ -f "$1" ] && grep -qsF "$2" "$1"; then
        return 0
    fi
    printf '\n# added by dep-lens install.sh\n%s\n' "$2" >> "$1"
    say "PATH entry added to $1"
}

case ":$PATH:" in
    *":${BIN_DIR}:"*)
        PATH_READY=yes
        ;;
    *)
        PATH_READY=no
        ;;
esac

LOGIN_SHELL="$(basename "${SHELL:-sh}")"
say "detected login shell: $LOGIN_SHELL"

if [ "$PATH_READY" = "no" ]; then
    case "$LOGIN_SHELL" in
        fish)
            if command -v fish >/dev/null 2>&1; then
                # Universal variable: persists across sessions, no config edit.
                fish -c "contains -- \"$BIN_DIR\" \$fish_user_paths; or fish_add_path -U \"$BIN_DIR\""
                say "PATH updated via fish_add_path (universal variable)"
            else
                say "fish reported as login shell but fish binary not found;"
                say "add $BIN_DIR to PATH manually."
            fi
            ;;
        zsh)
            add_line_once "${HOME}/.zshrc" "export PATH=\"\$HOME/.local/bin:\$PATH\""
            ;;
        bash)
            add_line_once "${HOME}/.bashrc" "export PATH=\"\$HOME/.local/bin:\$PATH\""
            ;;
        *)
            say "unknown shell '$LOGIN_SHELL': add $BIN_DIR to PATH manually."
            ;;
    esac
    say "open a new terminal (or re-source your shell config) for PATH to apply."
else
    say "PATH already contains $BIN_DIR"
fi

# fish keeps its own universal path list; if fish is installed, make sure it
# can see the launcher too, no matter which shell ran this script.
if command -v fish >/dev/null 2>&1; then
    fish -c "contains -- \"$BIN_DIR\" \$PATH; or fish_add_path -U \"$BIN_DIR\"" >/dev/null 2>&1 || true
fi

# ----------------------------------------------------------------- verify
say ""
say "verifying installation..."
"$LAUNCHER" --version
say ""
say "done. Try:"
say "  dep-lens                 interactive TUI for the current project"
say "  dep-lens --tr            Turkish UI"
say "  dep-lens --help          all flags and keys"
say "  ./install.sh --uninstall to remove"
