# dep-lens installer for native Windows (PowerShell): builds the Rust core
# and the Node CLI from this repository, installs a launcher into
# %LOCALAPPDATA%\dep-lens\bin, and adds that directory to your user PATH so
# the `dep-lens` command just works.
#
# Usage:
#   .\install.ps1               install or update
#   .\install.ps1 -Uninstall    remove the launcher
#
# WSL/Git-Bash users: use ./install.sh instead.

param(
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$BinDir   = Join-Path $env:LOCALAPPDATA 'dep-lens\bin'
$Launcher = Join-Path $BinDir 'dep-lens.cmd'

function Say($msg) { Write-Host $msg }
function Fail($msg) { Write-Error $msg; exit 1 }

# ---------------------------------------------------------------- uninstall
if ($Uninstall) {
    if (Test-Path $Launcher) {
        Remove-Item $Launcher -Force
        Say "removed $Launcher"
    } else {
        Say "nothing to remove: $Launcher does not exist"
    }
    Say "note: the PATH entry for $BinDir was left in place; it is harmless"
    Say "and shared with nothing else."
    exit 0
}

Say "[1/5] operating system: Windows ($($env:PROCESSOR_ARCHITECTURE))"

# ---------------------------------------------------------- prerequisites
function Test-Command($name) {
    return [bool](Get-Command $name -ErrorAction SilentlyContinue)
}

if (-not (Test-Command node))  { Fail "node not found. Install Node.js >= 18.18 first (https://nodejs.org)." }
if (-not (Test-Command npm))   { Fail "npm not found. It normally ships with Node.js." }
if (-not (Test-Command cargo)) { Fail "cargo not found. Install Rust from https://rustup.rs first." }

$nodeVersion = (node --version).TrimStart('v')
$nodeParts = $nodeVersion.Split('.')
$nodeMajor = [int]$nodeParts[0]
$nodeMinor = [int]$nodeParts[1]
if ($nodeMajor -lt 18 -or ($nodeMajor -eq 18 -and $nodeMinor -lt 18)) {
    Fail "Node.js >= 18.18 required, found v$nodeVersion."
}
$cargoVersion = (cargo --version)
Say "[2/5] prerequisites: node v$nodeVersion, $cargoVersion"

# ------------------------------------------------------------------ build
Say "[3/5] building Rust core (cargo build --release)..."
Push-Location $RepoRoot
try {
    cargo build --release --quiet
    if ($LASTEXITCODE -ne 0) { Fail "cargo build failed" }

    Say "[4/5] building Node CLI (npm install + tsc)..."
    npm install --silent
    if ($LASTEXITCODE -ne 0) { Fail "npm install failed" }
    npm run build:cli --silent
    if ($LASTEXITCODE -ne 0) { Fail "npm run build:cli failed" }
} finally {
    Pop-Location
}

$CoreBinary = Join-Path $RepoRoot 'target\release\dep-lens-core.exe'
$CliEntry   = Join-Path $RepoRoot 'packages\dep-lens\dist\cli.js'
if (-not (Test-Path $CoreBinary)) { Fail "build finished but $CoreBinary is missing" }
if (-not (Test-Path $CliEntry))   { Fail "build finished but $CliEntry is missing" }

# -------------------------------------------------------------- launcher
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null

$launcherContent = @"
@echo off
rem dep-lens launcher generated by install.ps1; points at the working tree at
rem $RepoRoot. Re-run install.ps1 after moving the repository.
set DEP_LENS_BINARY=$CoreBinary
node "$CliEntry" %*
"@
Set-Content -Path $Launcher -Value $launcherContent -Encoding ASCII
Say "[5/5] launcher installed: $Launcher"

# ------------------------------------------------------------------ PATH
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (($userPath -split ';') -notcontains $BinDir) {
    [Environment]::SetEnvironmentVariable('Path', "$userPath;$BinDir", 'User')
    Say "PATH updated: added $BinDir to your user PATH"
    Say "open a new terminal for PATH to apply."
} else {
    Say "PATH already contains $BinDir"
}

# Make the new binary available in this session too.
$env:Path = "$env:Path;$BinDir"

# ----------------------------------------------------------------- verify
Say ""
Say "verifying installation..."
& $Launcher --version

Say ""
Say "done. Try:"
Say "  dep-lens                 interactive TUI for the current project"
Say "  dep-lens --tr            Turkish UI"
Say "  dep-lens --help          all flags and keys"
Say "  .\install.ps1 -Uninstall to remove"
