use crate::model::Report;

/// Render a Markdown report (optimized for GitHub PR comments).
pub fn render(report: &Report) -> String {
    let mut out = String::new();
    out.push_str(&format!("# License Report: {}\n\n", report.project));
    out.push_str(&format!("- **Scanned At:** {}\n", report.scanned_at));
    out.push_str(&format!("- **Total Packages:** {}\n", report.summary.total));
    out.push_str(&format!(
        "- **Status:** {} Permissive, {} Weak, {} Strong, {} Unknown\n\n",
        report.summary.permissive,
        report.summary.weak_copyleft,
        report.summary.strong_copyleft,
        report.summary.unknown
    ));

    out.push_str("## Packages\n\n");
    out.push_str("| Package | Version | License | Category | Risk | Type |\n");
    out.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for pkg in &report.packages {
        let risk_icon = match pkg.risk_level {
            crate::model::RiskLevel::Low => "[OK]",
            crate::model::RiskLevel::Medium => "[!!]",
            crate::model::RiskLevel::High => "[XX]",
        };
        out.push_str(&format!(
            "| {} | {} | {} | {:?} | {} {} | {:?} |\n",
            pkg.name,
            pkg.version,
            pkg.license,
            pkg.category,
            risk_icon,
            pkg.risk_score,
            pkg.dependency_type
        ));
    }

    out.push_str("\n---\n*Generated by [dep-lens](https://github.com/dep-lens/dep-lens)*\n");
    out
}
